#!/bin/bash]
tlmgr install tabularx
tlmgr install xcolor
tlmgr install hyperref
tlmgr install cleveref
tlmgr install enumitem
tlmgr install amsmath
tlmgr install eurosym
tlmgr install ltablex
tlmgr install graphicx
tlmgr install gfsdidot
tlmgr install microtype
tlmgr install geometry
tlmgr install pdfpages
tlmgr install graphbox
tlmgr install float
tlmgr install longtable
tlmgr install array
tlmgr install fancyhdr
tlmgr install lastpage
tlmgr install calc
tlmgr install cm-super
tlmgr install lmodern
tlmgr install textcomp
tlmgr install caption
tlmgr install subcaption
tlmgr install rotating
tlmgr install changepage
tlmgr install amssymb
tlmgr install amsfonts
tlmgr install euler
tlmgr install amsthm
tlmgr install mathtools
tlmgr install listings
tlmgr install tikz
tlmgr install tikz-uml
tlmgr install booktabs
tlmgr install multirow
tlmgr install multicolumn
tlmgr install tocloft
tlmgr install appendix
tlmgr install parskip
tlmgr install titlesec
tlmgr install breakurl
tlmgr install blindtext
tlmgr install scrextend